/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface LineItem {
    description: string;
    quantity: number;
    unitPrice: number;
}
export interface JobStatusSummary {
    status: JobStatus;
    count: bigint;
}
export interface Invoice {
    id: bigint;
    issueDate: Time;
    lineItems: Array<LineItem>;
    total: number;
    paymentStatus: PaymentStatus;
    createdAt: Time;
    jobId?: bigint;
    dueDate: Time;
    updatedAt: Time;
    invoiceNumber: string;
    notes: string;
    customerId: bigint;
    taxRate: number;
    subtotal: number;
}
export interface StockUsageRecord {
    id: bigint;
    itemId: bigint;
    usedAt: Time;
    jobId: bigint;
    quantityUsed: bigint;
}
export interface DashboardStats {
    totalOpenJobs: bigint;
    totalTechnicians: bigint;
    totalRevenueThisMonth: number;
    totalJobs: bigint;
    pendingInvoices: bigint;
    completedJobsToday: bigint;
    totalCustomers: bigint;
}
export interface Technician {
    id: bigint;
    status: TechnicianStatus;
    name: string;
    createdAt: Time;
    email: string;
    updatedAt: Time;
    notes: string;
    specialization: string;
    phone: string;
    skills: Array<string>;
}
export interface Customer {
    id: bigint;
    customerType: CustomerType;
    name: string;
    createdAt: Time;
    email: string;
    updatedAt: Time;
    company: string;
    address: string;
    notes: string;
    phone: string;
}
export interface InventoryItem {
    id: bigint;
    sku: string;
    quantityInStock: bigint;
    supplier: string;
    name: string;
    createdAt: Time;
    minimumStockThreshold: bigint;
    updatedAt: Time;
    notes: string;
    category: string;
    unitCost: number;
}
export interface TechnicianPerformance {
    completedJobs: bigint;
    technicianName: string;
    technicianId: bigint;
    assignedJobs: bigint;
}
export interface Job {
    id: bigint;
    status: JobStatus;
    title: string;
    scheduledDate?: Time;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    notes: string;
    customerId: bigint;
    priority: JobPriority;
    location: string;
    assignedTechnician?: bigint;
}
export interface InventoryUsageSummary {
    itemId: bigint;
    totalUsed: bigint;
    itemName: string;
}
export interface RevenueByMonth {
    month: string;
    collected: number;
    invoiced: number;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export enum CustomerType {
    commercial = "commercial",
    residential = "residential"
}
export enum JobPriority {
    low = "low",
    high = "high",
    urgent = "urgent",
    medium = "medium"
}
export enum JobStatus {
    new_ = "new",
    cancelled = "cancelled",
    completed = "completed",
    inProgress = "inProgress",
    onHold = "onHold"
}
export enum PaymentStatus {
    paid = "paid",
    unpaid = "unpaid",
    overdue = "overdue",
    partial = "partial"
}
export enum TechnicianStatus {
    active = "active",
    inactive = "inactive"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCustomer(customer: Customer): Promise<bigint>;
    createInventoryItem(item: InventoryItem): Promise<bigint>;
    createInvoice(invoice: Invoice): Promise<bigint>;
    createJob(job: Job): Promise<bigint>;
    createTechnician(technician: Technician): Promise<bigint>;
    deactivateTechnician(id: bigint): Promise<void>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteInventoryItem(id: bigint): Promise<void>;
    deleteInvoice(id: bigint): Promise<void>;
    deleteJob(id: bigint): Promise<void>;
    deleteTechnician(id: bigint): Promise<void>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllInventoryItems(): Promise<Array<InventoryItem>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllJobs(): Promise<Array<Job>>;
    getAllPriorities(): Promise<Array<JobPriority>>;
    getAllStatuses(): Promise<Array<JobStatus>>;
    getAllTechnicians(): Promise<Array<Technician>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: bigint): Promise<Customer | null>;
    getDashboardStats(): Promise<DashboardStats>;
    getInventoryItem(id: bigint): Promise<InventoryItem | null>;
    getInventoryUsageReport(): Promise<Array<InventoryUsageSummary>>;
    getInvoice(id: bigint): Promise<Invoice | null>;
    getInvoicesByCustomer(customerId: bigint): Promise<Array<Invoice>>;
    getInvoicesByStatus(status: PaymentStatus): Promise<Array<Invoice>>;
    getJob(id: bigint): Promise<Job | null>;
    getJobStatusSummary(): Promise<Array<JobStatusSummary>>;
    getJobsByCustomer(customerId: bigint): Promise<Array<Job>>;
    getJobsByDateRange(start: Time, end: Time): Promise<Array<Job>>;
    getJobsByPriority(priority: JobPriority): Promise<Array<Job>>;
    getJobsByStatus(status: JobStatus): Promise<Array<Job>>;
    getJobsByTechnician(techId: bigint): Promise<Array<Job>>;
    getLowStockItems(): Promise<Array<InventoryItem>>;
    getRevenueReport(): Promise<Array<RevenueByMonth>>;
    getStockUsageByJob(jobId: bigint): Promise<Array<StockUsageRecord>>;
    getTechnician(id: bigint): Promise<Technician | null>;
    getTechnicianPerformance(): Promise<Array<TechnicianPerformance>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markInvoicePaid(id: bigint): Promise<void>;
    recordStockUsage(itemId: bigint, jobId: bigint, quantityUsed: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchCustomers(searchText: string): Promise<Array<Customer>>;
    updateCustomer(id: bigint, customer: Customer): Promise<void>;
    updateInventoryItem(id: bigint, item: InventoryItem): Promise<void>;
    updateInvoice(id: bigint, invoice: Invoice): Promise<void>;
    updateJob(id: bigint, job: Job): Promise<void>;
    updateTechnician(id: bigint, technician: Technician): Promise<void>;
}
import type { Customer as _Customer, CustomerType as _CustomerType, InventoryItem as _InventoryItem, Invoice as _Invoice, Job as _Job, JobPriority as _JobPriority, JobStatus as _JobStatus, JobStatusSummary as _JobStatusSummary, LineItem as _LineItem, PaymentStatus as _PaymentStatus, Technician as _Technician, TechnicianStatus as _TechnicianStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomer(arg0: Customer): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(to_candid_Customer_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(to_candid_Customer_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createInventoryItem(arg0: InventoryItem): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventoryItem(arg0);
            return result;
        }
    }
    async createInvoice(arg0: Invoice): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_Invoice_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_Invoice_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createJob(arg0: Job): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(to_candid_Job_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(to_candid_Job_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTechnician(arg0: Technician): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTechnician(to_candid_Technician_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTechnician(to_candid_Technician_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deactivateTechnician(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateTechnician(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateTechnician(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteInventoryItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteTechnician(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTechnician(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTechnician(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventoryItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventoryItems();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPriorities(): Promise<Array<JobPriority>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPriorities();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPriorities();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStatuses(): Promise<Array<JobStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStatuses();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStatuses();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTechnicians(): Promise<Array<Technician>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTechnicians();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTechnicians();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getInventoryItem(arg0: bigint): Promise<InventoryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryUsageReport(): Promise<Array<InventoryUsageSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryUsageReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryUsageReport();
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByCustomer(arg0: bigint): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByCustomer(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByCustomer(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByStatus(arg0: PaymentStatus): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByStatus(to_candid_PaymentStatus_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByStatus(to_candid_PaymentStatus_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: bigint): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobStatusSummary(): Promise<Array<JobStatusSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobStatusSummary();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobStatusSummary();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByCustomer(arg0: bigint): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByCustomer(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByCustomer(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByDateRange(arg0: Time, arg1: Time): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByDateRange(arg0, arg1);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByDateRange(arg0, arg1);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByPriority(arg0: JobPriority): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByPriority(to_candid_JobPriority_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByPriority(to_candid_JobPriority_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByStatus(arg0: JobStatus): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByStatus(to_candid_JobStatus_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByStatus(to_candid_JobStatus_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByTechnician(arg0: bigint): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByTechnician(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByTechnician(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockItems();
            return result;
        }
    }
    async getRevenueReport(): Promise<Array<RevenueByMonth>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueReport();
            return result;
        }
    }
    async getStockUsageByJob(arg0: bigint): Promise<Array<StockUsageRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockUsageByJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockUsageByJob(arg0);
            return result;
        }
    }
    async getTechnician(arg0: bigint): Promise<Technician | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechnician(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechnician(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTechnicianPerformance(): Promise<Array<TechnicianPerformance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechnicianPerformance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechnicianPerformance();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markInvoicePaid(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markInvoicePaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markInvoicePaid(arg0);
            return result;
        }
    }
    async recordStockUsage(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordStockUsage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordStockUsage(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchCustomers(arg0: string): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCustomers(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCustomers(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomer(arg0: bigint, arg1: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, to_candid_Customer_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, to_candid_Customer_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateInventoryItem(arg0: bigint, arg1: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, arg1);
            return result;
        }
    }
    async updateInvoice(arg0: bigint, arg1: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, to_candid_Invoice_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, to_candid_Invoice_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateJob(arg0: bigint, arg1: Job): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, to_candid_Job_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, to_candid_Job_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTechnician(arg0: bigint, arg1: Technician): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTechnician(arg0, to_candid_Technician_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTechnician(arg0, to_candid_Technician_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CustomerType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerType): CustomerType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_JobPriority_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPriority): JobPriority {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatusSummary_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatusSummary): JobStatusSummary {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TechnicianStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TechnicianStatus): TechnicianStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Technician_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Technician): Technician {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryItem]): InventoryItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Technician]): Technician | null {
    return value.length === 0 ? null : from_candid_Technician_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerType: _CustomerType;
    name: string;
    createdAt: _Time;
    email: string;
    updatedAt: _Time;
    company: string;
    address: string;
    notes: string;
    phone: string;
}): {
    id: bigint;
    customerType: CustomerType;
    name: string;
    createdAt: Time;
    email: string;
    updatedAt: Time;
    company: string;
    address: string;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        customerType: from_candid_CustomerType_n24(_uploadFile, _downloadFile, value.customerType),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        company: value.company,
        address: value.address,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    issueDate: _Time;
    lineItems: Array<_LineItem>;
    total: number;
    paymentStatus: _PaymentStatus;
    createdAt: _Time;
    jobId: [] | [bigint];
    dueDate: _Time;
    updatedAt: _Time;
    invoiceNumber: string;
    notes: string;
    customerId: bigint;
    taxRate: number;
    subtotal: number;
}): {
    id: bigint;
    issueDate: Time;
    lineItems: Array<LineItem>;
    total: number;
    paymentStatus: PaymentStatus;
    createdAt: Time;
    jobId?: bigint;
    dueDate: Time;
    updatedAt: Time;
    invoiceNumber: string;
    notes: string;
    customerId: bigint;
    taxRate: number;
    subtotal: number;
} {
    return {
        id: value.id,
        issueDate: value.issueDate,
        lineItems: value.lineItems,
        total: value.total,
        paymentStatus: from_candid_PaymentStatus_n29(_uploadFile, _downloadFile, value.paymentStatus),
        createdAt: value.createdAt,
        jobId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.jobId)),
        dueDate: value.dueDate,
        updatedAt: value.updatedAt,
        invoiceNumber: value.invoiceNumber,
        notes: value.notes,
        customerId: value.customerId,
        taxRate: value.taxRate,
        subtotal: value.subtotal
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _JobStatus;
    title: string;
    scheduledDate: [] | [_Time];
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    notes: string;
    customerId: bigint;
    priority: _JobPriority;
    location: string;
    assignedTechnician: [] | [bigint];
}): {
    id: bigint;
    status: JobStatus;
    title: string;
    scheduledDate?: Time;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    notes: string;
    customerId: bigint;
    priority: JobPriority;
    location: string;
    assignedTechnician?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n35(_uploadFile, _downloadFile, value.status),
        title: value.title,
        scheduledDate: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.scheduledDate)),
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        notes: value.notes,
        customerId: value.customerId,
        priority: from_candid_JobPriority_n38(_uploadFile, _downloadFile, value.priority),
        location: value.location,
        assignedTechnician: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.assignedTechnician))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TechnicianStatus;
    name: string;
    createdAt: _Time;
    email: string;
    updatedAt: _Time;
    notes: string;
    specialization: string;
    phone: string;
    skills: Array<string>;
}): {
    id: bigint;
    status: TechnicianStatus;
    name: string;
    createdAt: Time;
    email: string;
    updatedAt: Time;
    notes: string;
    specialization: string;
    phone: string;
    skills: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_TechnicianStatus_n45(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        notes: value.notes,
        specialization: value.specialization,
        phone: value.phone,
        skills: value.skills
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _JobStatus;
    count: bigint;
}): {
    status: JobStatus;
    count: bigint;
} {
    return {
        status: from_candid_JobStatus_n35(_uploadFile, _downloadFile, value.status),
        count: value.count
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    residential: null;
}): CustomerType {
    return "commercial" in value ? CustomerType.commercial : "residential" in value ? CustomerType.residential : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
} | {
    overdue: null;
} | {
    partial: null;
}): PaymentStatus {
    return "paid" in value ? PaymentStatus.paid : "unpaid" in value ? PaymentStatus.unpaid : "overdue" in value ? PaymentStatus.overdue : "partial" in value ? PaymentStatus.partial : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    onHold: null;
}): JobStatus {
    return "new" in value ? JobStatus.new : "cancelled" in value ? JobStatus.cancelled : "completed" in value ? JobStatus.completed : "inProgress" in value ? JobStatus.inProgress : "onHold" in value ? JobStatus.onHold : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    urgent: null;
} | {
    medium: null;
}): JobPriority {
    return "low" in value ? JobPriority.low : "high" in value ? JobPriority.high : "urgent" in value ? JobPriority.urgent : "medium" in value ? JobPriority.medium : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): TechnicianStatus {
    return "active" in value ? TechnicianStatus.active : "inactive" in value ? TechnicianStatus.inactive : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPriority>): Array<JobPriority> {
    return value.map((x)=>from_candid_JobPriority_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobStatus>): Array<JobStatus> {
    return value.map((x)=>from_candid_JobStatus_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Technician>): Array<Technician> {
    return value.map((x)=>from_candid_Technician_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobStatusSummary>): Array<JobStatusSummary> {
    return value.map((x)=>from_candid_JobStatusSummary_n55(_uploadFile, _downloadFile, x));
}
function to_candid_CustomerType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerType): _CustomerType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Customer_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Customer): _Customer {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Invoice_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_JobPriority_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobPriority): _JobPriority {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Job_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Job): _Job {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_TechnicianStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TechnicianStatus): _TechnicianStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Technician_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Technician): _Technician {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: JobStatus;
    title: string;
    scheduledDate?: Time;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    notes: string;
    customerId: bigint;
    priority: JobPriority;
    location: string;
    assignedTechnician?: bigint;
}): {
    id: bigint;
    status: _JobStatus;
    title: string;
    scheduledDate: [] | [_Time];
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    notes: string;
    customerId: bigint;
    priority: _JobPriority;
    location: string;
    assignedTechnician: [] | [bigint];
} {
    return {
        id: value.id,
        status: to_candid_JobStatus_n13(_uploadFile, _downloadFile, value.status),
        title: value.title,
        scheduledDate: value.scheduledDate ? candid_some(value.scheduledDate) : candid_none(),
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        notes: value.notes,
        customerId: value.customerId,
        priority: to_candid_JobPriority_n15(_uploadFile, _downloadFile, value.priority),
        location: value.location,
        assignedTechnician: value.assignedTechnician ? candid_some(value.assignedTechnician) : candid_none()
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: TechnicianStatus;
    name: string;
    createdAt: Time;
    email: string;
    updatedAt: Time;
    notes: string;
    specialization: string;
    phone: string;
    skills: Array<string>;
}): {
    id: bigint;
    status: _TechnicianStatus;
    name: string;
    createdAt: _Time;
    email: string;
    updatedAt: _Time;
    notes: string;
    specialization: string;
    phone: string;
    skills: Array<string>;
} {
    return {
        id: value.id,
        status: to_candid_TechnicianStatus_n19(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        notes: value.notes,
        specialization: value.specialization,
        phone: value.phone,
        skills: value.skills
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerType: CustomerType;
    name: string;
    createdAt: Time;
    email: string;
    updatedAt: Time;
    company: string;
    address: string;
    notes: string;
    phone: string;
}): {
    id: bigint;
    customerType: _CustomerType;
    name: string;
    createdAt: _Time;
    email: string;
    updatedAt: _Time;
    company: string;
    address: string;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        customerType: to_candid_CustomerType_n5(_uploadFile, _downloadFile, value.customerType),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        company: value.company,
        address: value.address,
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    issueDate: Time;
    lineItems: Array<LineItem>;
    total: number;
    paymentStatus: PaymentStatus;
    createdAt: Time;
    jobId?: bigint;
    dueDate: Time;
    updatedAt: Time;
    invoiceNumber: string;
    notes: string;
    customerId: bigint;
    taxRate: number;
    subtotal: number;
}): {
    id: bigint;
    issueDate: _Time;
    lineItems: Array<_LineItem>;
    total: number;
    paymentStatus: _PaymentStatus;
    createdAt: _Time;
    jobId: [] | [bigint];
    dueDate: _Time;
    updatedAt: _Time;
    invoiceNumber: string;
    notes: string;
    customerId: bigint;
    taxRate: number;
    subtotal: number;
} {
    return {
        id: value.id,
        issueDate: value.issueDate,
        lineItems: value.lineItems,
        total: value.total,
        paymentStatus: to_candid_PaymentStatus_n9(_uploadFile, _downloadFile, value.paymentStatus),
        createdAt: value.createdAt,
        jobId: value.jobId ? candid_some(value.jobId) : candid_none(),
        dueDate: value.dueDate,
        updatedAt: value.updatedAt,
        invoiceNumber: value.invoiceNumber,
        notes: value.notes,
        customerId: value.customerId,
        taxRate: value.taxRate,
        subtotal: value.subtotal
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    paid: null;
} | {
    unpaid: null;
} | {
    overdue: null;
} | {
    partial: null;
} {
    return value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.unpaid ? {
        unpaid: null
    } : value == PaymentStatus.overdue ? {
        overdue: null
    } : value == PaymentStatus.partial ? {
        partial: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    new: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    onHold: null;
} {
    return value == JobStatus.new ? {
        new_: null
    } : value == JobStatus.cancelled ? {
        cancelled: null
    } : value == JobStatus.completed ? {
        completed: null
    } : value == JobStatus.inProgress ? {
        inProgress: null
    } : value == JobStatus.onHold ? {
        onHold: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobPriority): {
    low: null;
} | {
    high: null;
} | {
    urgent: null;
} | {
    medium: null;
} {
    return value == JobPriority.low ? {
        low: null
    } : value == JobPriority.high ? {
        high: null
    } : value == JobPriority.urgent ? {
        urgent: null
    } : value == JobPriority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TechnicianStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == TechnicianStatus.active ? {
        active: null
    } : value == TechnicianStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerType): {
    commercial: null;
} | {
    residential: null;
} {
    return value == CustomerType.commercial ? {
        commercial: null
    } : value == CustomerType.residential ? {
        residential: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
