/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'customerType' : CustomerType,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'updatedAt' : Time,
  'company' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export type CustomerType = { 'commercial' : null } |
  { 'residential' : null };
export interface DashboardStats {
  'totalOpenJobs' : bigint,
  'totalTechnicians' : bigint,
  'totalRevenueThisMonth' : number,
  'totalJobs' : bigint,
  'pendingInvoices' : bigint,
  'completedJobsToday' : bigint,
  'totalCustomers' : bigint,
}
export interface InventoryItem {
  'id' : bigint,
  'sku' : string,
  'quantityInStock' : bigint,
  'supplier' : string,
  'name' : string,
  'createdAt' : Time,
  'minimumStockThreshold' : bigint,
  'updatedAt' : Time,
  'notes' : string,
  'category' : string,
  'unitCost' : number,
}
export interface InventoryUsageSummary {
  'itemId' : bigint,
  'totalUsed' : bigint,
  'itemName' : string,
}
export interface Invoice {
  'id' : bigint,
  'issueDate' : Time,
  'lineItems' : Array<LineItem>,
  'total' : number,
  'paymentStatus' : PaymentStatus,
  'createdAt' : Time,
  'jobId' : [] | [bigint],
  'dueDate' : Time,
  'updatedAt' : Time,
  'invoiceNumber' : string,
  'notes' : string,
  'customerId' : bigint,
  'taxRate' : number,
  'subtotal' : number,
}
export interface Job {
  'id' : bigint,
  'status' : JobStatus,
  'title' : string,
  'scheduledDate' : [] | [Time],
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'notes' : string,
  'customerId' : bigint,
  'priority' : JobPriority,
  'location' : string,
  'assignedTechnician' : [] | [bigint],
}
export type JobPriority = { 'low' : null } |
  { 'high' : null } |
  { 'urgent' : null } |
  { 'medium' : null };
export type JobStatus = { 'new' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'onHold' : null };
export interface JobStatusSummary { 'status' : JobStatus, 'count' : bigint }
export interface LineItem {
  'description' : string,
  'quantity' : number,
  'unitPrice' : number,
}
export type PaymentStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'overdue' : null } |
  { 'partial' : null };
export interface RevenueByMonth {
  'month' : string,
  'collected' : number,
  'invoiced' : number,
}
export interface StockUsageRecord {
  'id' : bigint,
  'itemId' : bigint,
  'usedAt' : Time,
  'jobId' : bigint,
  'quantityUsed' : bigint,
}
export interface Technician {
  'id' : bigint,
  'status' : TechnicianStatus,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'updatedAt' : Time,
  'notes' : string,
  'specialization' : string,
  'phone' : string,
  'skills' : Array<string>,
}
export interface TechnicianPerformance {
  'completedJobs' : bigint,
  'technicianName' : string,
  'technicianId' : bigint,
  'assignedJobs' : bigint,
}
export type TechnicianStatus = { 'active' : null } |
  { 'inactive' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomer' : ActorMethod<[Customer], bigint>,
  'createInventoryItem' : ActorMethod<[InventoryItem], bigint>,
  'createInvoice' : ActorMethod<[Invoice], bigint>,
  'createJob' : ActorMethod<[Job], bigint>,
  'createTechnician' : ActorMethod<[Technician], bigint>,
  'deactivateTechnician' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteInventoryItem' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'deleteTechnician' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getAllPriorities' : ActorMethod<[], Array<JobPriority>>,
  'getAllStatuses' : ActorMethod<[], Array<JobStatus>>,
  'getAllTechnicians' : ActorMethod<[], Array<Technician>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getInventoryItem' : ActorMethod<[bigint], [] | [InventoryItem]>,
  'getInventoryUsageReport' : ActorMethod<[], Array<InventoryUsageSummary>>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getInvoicesByCustomer' : ActorMethod<[bigint], Array<Invoice>>,
  'getInvoicesByStatus' : ActorMethod<[PaymentStatus], Array<Invoice>>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getJobStatusSummary' : ActorMethod<[], Array<JobStatusSummary>>,
  'getJobsByCustomer' : ActorMethod<[bigint], Array<Job>>,
  'getJobsByDateRange' : ActorMethod<[Time, Time], Array<Job>>,
  'getJobsByPriority' : ActorMethod<[JobPriority], Array<Job>>,
  'getJobsByStatus' : ActorMethod<[JobStatus], Array<Job>>,
  'getJobsByTechnician' : ActorMethod<[bigint], Array<Job>>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getRevenueReport' : ActorMethod<[], Array<RevenueByMonth>>,
  'getStockUsageByJob' : ActorMethod<[bigint], Array<StockUsageRecord>>,
  'getTechnician' : ActorMethod<[bigint], [] | [Technician]>,
  'getTechnicianPerformance' : ActorMethod<[], Array<TechnicianPerformance>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markInvoicePaid' : ActorMethod<[bigint], undefined>,
  'recordStockUsage' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCustomers' : ActorMethod<[string], Array<Customer>>,
  'updateCustomer' : ActorMethod<[bigint, Customer], undefined>,
  'updateInventoryItem' : ActorMethod<[bigint, InventoryItem], undefined>,
  'updateInvoice' : ActorMethod<[bigint, Invoice], undefined>,
  'updateJob' : ActorMethod<[bigint, Job], undefined>,
  'updateTechnician' : ActorMethod<[bigint, Technician], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];