/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerType = IDL.Variant({
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
});
export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'customerType' : CustomerType,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'company' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'quantityInStock' : IDL.Nat,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'minimumStockThreshold' : IDL.Nat,
  'updatedAt' : Time,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'unitCost' : IDL.Float64,
});
export const LineItem = IDL.Record({
  'description' : IDL.Text,
  'quantity' : IDL.Float64,
  'unitPrice' : IDL.Float64,
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'overdue' : IDL.Null,
  'partial' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'issueDate' : Time,
  'lineItems' : IDL.Vec(LineItem),
  'total' : IDL.Float64,
  'paymentStatus' : PaymentStatus,
  'createdAt' : Time,
  'jobId' : IDL.Opt(IDL.Nat),
  'dueDate' : Time,
  'updatedAt' : Time,
  'invoiceNumber' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
  'taxRate' : IDL.Float64,
  'subtotal' : IDL.Float64,
});
export const JobStatus = IDL.Variant({
  'new' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'onHold' : IDL.Null,
});
export const JobPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
  'medium' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'status' : JobStatus,
  'title' : IDL.Text,
  'scheduledDate' : IDL.Opt(Time),
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
  'priority' : JobPriority,
  'location' : IDL.Text,
  'assignedTechnician' : IDL.Opt(IDL.Nat),
});
export const TechnicianStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Technician = IDL.Record({
  'id' : IDL.Nat,
  'status' : TechnicianStatus,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'notes' : IDL.Text,
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalOpenJobs' : IDL.Nat,
  'totalTechnicians' : IDL.Nat,
  'totalRevenueThisMonth' : IDL.Float64,
  'totalJobs' : IDL.Nat,
  'pendingInvoices' : IDL.Nat,
  'completedJobsToday' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
});
export const InventoryUsageSummary = IDL.Record({
  'itemId' : IDL.Nat,
  'totalUsed' : IDL.Nat,
  'itemName' : IDL.Text,
});
export const JobStatusSummary = IDL.Record({
  'status' : JobStatus,
  'count' : IDL.Nat,
});
export const RevenueByMonth = IDL.Record({
  'month' : IDL.Text,
  'collected' : IDL.Float64,
  'invoiced' : IDL.Float64,
});
export const StockUsageRecord = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'usedAt' : Time,
  'jobId' : IDL.Nat,
  'quantityUsed' : IDL.Nat,
});
export const TechnicianPerformance = IDL.Record({
  'completedJobs' : IDL.Nat,
  'technicianName' : IDL.Text,
  'technicianId' : IDL.Nat,
  'assignedJobs' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func([Customer], [IDL.Nat], []),
  'createInventoryItem' : IDL.Func([InventoryItem], [IDL.Nat], []),
  'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
  'createJob' : IDL.Func([Job], [IDL.Nat], []),
  'createTechnician' : IDL.Func([Technician], [IDL.Nat], []),
  'deactivateTechnician' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'deleteTechnician' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getAllPriorities' : IDL.Func([], [IDL.Vec(JobPriority)], ['query']),
  'getAllStatuses' : IDL.Func([], [IDL.Vec(JobStatus)], ['query']),
  'getAllTechnicians' : IDL.Func([], [IDL.Vec(Technician)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getInventoryItem' : IDL.Func([IDL.Nat], [IDL.Opt(InventoryItem)], ['query']),
  'getInventoryUsageReport' : IDL.Func(
      [],
      [IDL.Vec(InventoryUsageSummary)],
      ['query'],
    ),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getInvoicesByCustomer' : IDL.Func([IDL.Nat], [IDL.Vec(Invoice)], ['query']),
  'getInvoicesByStatus' : IDL.Func(
      [PaymentStatus],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getJobStatusSummary' : IDL.Func([], [IDL.Vec(JobStatusSummary)], ['query']),
  'getJobsByCustomer' : IDL.Func([IDL.Nat], [IDL.Vec(Job)], ['query']),
  'getJobsByDateRange' : IDL.Func([Time, Time], [IDL.Vec(Job)], ['query']),
  'getJobsByPriority' : IDL.Func([JobPriority], [IDL.Vec(Job)], ['query']),
  'getJobsByStatus' : IDL.Func([JobStatus], [IDL.Vec(Job)], ['query']),
  'getJobsByTechnician' : IDL.Func([IDL.Nat], [IDL.Vec(Job)], ['query']),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getRevenueReport' : IDL.Func([], [IDL.Vec(RevenueByMonth)], ['query']),
  'getStockUsageByJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StockUsageRecord)],
      ['query'],
    ),
  'getTechnician' : IDL.Func([IDL.Nat], [IDL.Opt(Technician)], ['query']),
  'getTechnicianPerformance' : IDL.Func(
      [],
      [IDL.Vec(TechnicianPerformance)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markInvoicePaid' : IDL.Func([IDL.Nat], [], []),
  'recordStockUsage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
  'updateCustomer' : IDL.Func([IDL.Nat, Customer], [], []),
  'updateInventoryItem' : IDL.Func([IDL.Nat, InventoryItem], [], []),
  'updateInvoice' : IDL.Func([IDL.Nat, Invoice], [], []),
  'updateJob' : IDL.Func([IDL.Nat, Job], [], []),
  'updateTechnician' : IDL.Func([IDL.Nat, Technician], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerType = IDL.Variant({
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
  });
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'customerType' : CustomerType,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'company' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'quantityInStock' : IDL.Nat,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'minimumStockThreshold' : IDL.Nat,
    'updatedAt' : Time,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'unitCost' : IDL.Float64,
  });
  const LineItem = IDL.Record({
    'description' : IDL.Text,
    'quantity' : IDL.Float64,
    'unitPrice' : IDL.Float64,
  });
  const PaymentStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'overdue' : IDL.Null,
    'partial' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'issueDate' : Time,
    'lineItems' : IDL.Vec(LineItem),
    'total' : IDL.Float64,
    'paymentStatus' : PaymentStatus,
    'createdAt' : Time,
    'jobId' : IDL.Opt(IDL.Nat),
    'dueDate' : Time,
    'updatedAt' : Time,
    'invoiceNumber' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
    'taxRate' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  const JobStatus = IDL.Variant({
    'new' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'onHold' : IDL.Null,
  });
  const JobPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'status' : JobStatus,
    'title' : IDL.Text,
    'scheduledDate' : IDL.Opt(Time),
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
    'priority' : JobPriority,
    'location' : IDL.Text,
    'assignedTechnician' : IDL.Opt(IDL.Nat),
  });
  const TechnicianStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Technician = IDL.Record({
    'id' : IDL.Nat,
    'status' : TechnicianStatus,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'notes' : IDL.Text,
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalOpenJobs' : IDL.Nat,
    'totalTechnicians' : IDL.Nat,
    'totalRevenueThisMonth' : IDL.Float64,
    'totalJobs' : IDL.Nat,
    'pendingInvoices' : IDL.Nat,
    'completedJobsToday' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
  });
  const InventoryUsageSummary = IDL.Record({
    'itemId' : IDL.Nat,
    'totalUsed' : IDL.Nat,
    'itemName' : IDL.Text,
  });
  const JobStatusSummary = IDL.Record({
    'status' : JobStatus,
    'count' : IDL.Nat,
  });
  const RevenueByMonth = IDL.Record({
    'month' : IDL.Text,
    'collected' : IDL.Float64,
    'invoiced' : IDL.Float64,
  });
  const StockUsageRecord = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : IDL.Nat,
    'usedAt' : Time,
    'jobId' : IDL.Nat,
    'quantityUsed' : IDL.Nat,
  });
  const TechnicianPerformance = IDL.Record({
    'completedJobs' : IDL.Nat,
    'technicianName' : IDL.Text,
    'technicianId' : IDL.Nat,
    'assignedJobs' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func([Customer], [IDL.Nat], []),
    'createInventoryItem' : IDL.Func([InventoryItem], [IDL.Nat], []),
    'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
    'createJob' : IDL.Func([Job], [IDL.Nat], []),
    'createTechnician' : IDL.Func([Technician], [IDL.Nat], []),
    'deactivateTechnician' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'deleteTechnician' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getAllPriorities' : IDL.Func([], [IDL.Vec(JobPriority)], ['query']),
    'getAllStatuses' : IDL.Func([], [IDL.Vec(JobStatus)], ['query']),
    'getAllTechnicians' : IDL.Func([], [IDL.Vec(Technician)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getInventoryItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InventoryItem)],
        ['query'],
      ),
    'getInventoryUsageReport' : IDL.Func(
        [],
        [IDL.Vec(InventoryUsageSummary)],
        ['query'],
      ),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getInvoicesByCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getInvoicesByStatus' : IDL.Func(
        [PaymentStatus],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getJobStatusSummary' : IDL.Func(
        [],
        [IDL.Vec(JobStatusSummary)],
        ['query'],
      ),
    'getJobsByCustomer' : IDL.Func([IDL.Nat], [IDL.Vec(Job)], ['query']),
    'getJobsByDateRange' : IDL.Func([Time, Time], [IDL.Vec(Job)], ['query']),
    'getJobsByPriority' : IDL.Func([JobPriority], [IDL.Vec(Job)], ['query']),
    'getJobsByStatus' : IDL.Func([JobStatus], [IDL.Vec(Job)], ['query']),
    'getJobsByTechnician' : IDL.Func([IDL.Nat], [IDL.Vec(Job)], ['query']),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getRevenueReport' : IDL.Func([], [IDL.Vec(RevenueByMonth)], ['query']),
    'getStockUsageByJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StockUsageRecord)],
        ['query'],
      ),
    'getTechnician' : IDL.Func([IDL.Nat], [IDL.Opt(Technician)], ['query']),
    'getTechnicianPerformance' : IDL.Func(
        [],
        [IDL.Vec(TechnicianPerformance)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markInvoicePaid' : IDL.Func([IDL.Nat], [], []),
    'recordStockUsage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
    'updateCustomer' : IDL.Func([IDL.Nat, Customer], [], []),
    'updateInventoryItem' : IDL.Func([IDL.Nat, InventoryItem], [], []),
    'updateInvoice' : IDL.Func([IDL.Nat, Invoice], [], []),
    'updateJob' : IDL.Func([IDL.Nat, Job], [], []),
    'updateTechnician' : IDL.Func([IDL.Nat, Technician], [], []),
  });
};

export const init = ({ IDL }) => { return []; };